AWSTemplateFormatVersion: "2010-09-09"
Description: "Small Test App Example Template"
Parameters:
  vpcID:
    Description: "VPC ID"
    Type: "AWS::EC2::VPC::Id"
  subnetID:
    Description: "VPC Subnet IDs"
    Type: "AWS::EC2::Subnet::Id"
  appVersion:
    Description: "Application version"
    Type: "String"
  updateQueueUrl:
    Description: "SQS Queue URL"
    Type: "String"
Resources:
  testQueue:
    Type: "AWS::SQS::Queue"
  secGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Test Group"
      VpcId: "|Ref|vpcID"
  WebServerInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-6e7bd919"
      SecurityGroupIds:
        - "|GetAtt|secGroup|GroupId"
      SubnetId: "|Ref|subnetID"
      InstanceType: "t2.micro"
      "@TaupageUserData@":
        application_id: "|Ref|AWS::StackName"
        application_version: "|Ref|appVersion"
        environment:
          JOB_QUEUE: "|Ref|testQueue"
          UPDATE_QUEUE: "|Ref|updateQueueUrl"
