sudo: false
language: python
python:
- '3.4'
- '3.5'
- '3.6'
before_install:
- git fetch --unshallow
install:
- pip install pip pybuilder coveralls --upgrade
- pyb install_dependencies
script:
- pyb -X run_unit_tests
after_success:
- coveralls --verbose
before_deploy:
- pyb -X package
deploy:
  provider: pypi
  distributions: sdist
  skip_cleanup: true
  on:
    repo: KCOM-Enterprise/cfn-square
    branch: master
    python: '3.5'
  user: nathanreynolds-kcom
  password:
    # To update the PyPI password:
    #   $ cd cfn-square
    #   $ docker run -v $PWD:/project caktux/travis-cli encrypt $YOUR_PYPI_PASSWORD --add deploy.password
    # See <https://docs.travis-ci.com/user/deployment/pypi/>
    secure: Iubsc6DEpx+DS/XL45lmUB8/z2MDlWawJRiA/4cRkSKV087wPBetgeKBMObPipv7kvD04zIXIUR3gIA568oQ1HX/DPFJkwgFLCOOuuNNhS8I9o3s33oQM0xxpC+8VV1WawwNDHaMScv4WWcPceERnZbeIgKAt8QsO5smEIRAkO2uueTwaP+kzpKaIo4AqYKbrcPVd7kYrEr6kzxKd7xLvF5azbpJ4BKBwSTiJNneOx03PiFsexjdRKA84a3BXoAT4v3pq9pR2SHouNnLdD02HPluccbgxEUqYYCIjXBWPaN4yiqk8cML7FawI+XfZtNCci/H5qM9u9ZB5AmElOmD8xYaCSjvuVddADz8X7D1vHOEJRnATtMkgQ+JO3iekxUFayfKMIpphHDvyhRXs6qrzbr2Bf49u4HA1YjEqcnXCQTyCV0JkMN8IQogPpVk74nuavp1ioPYC2+i7pzMnUQEVAFYlDMzYBAfNOCICUQuVEysyAuQFoPkz14sXHKOwFCfL+ch9+w0UC4wf3UFmQy/E7N7Gy1yNzzjWU7DzQowkeTP7hKKW8OejpKj9cXnnE+Hb4jo1HResAvwovW93b9mj2zObDCSov9prZzEMdYD4vbfkMgAx6QRj/pIlbkkKiNxNrv9Xv5eSgmz9f9+mCYpZzPvMlsRtKwtCfXj1EhP0nw=
