sudo: false
language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- pypy
before_install:
- git fetch --unshallow
install:
- pip install pip pybuilder coveralls --upgrade
- pyb install_dependencies
script:
- pyb -X run_unit_tests
after_success:
- coveralls --verbose
before_deploy:
- pyb -X package
deploy:
  provider: pypi
  user: steveparker-kcom
  password:
    secure: t94MDd1rLDAL6hk9FJO3VUmP5j9TWIlIsl/ShU6sqx26Mf9CS+w4sKaHvQUaC6GnyiyOmYoWP1mVfLbX+UI0X3QWoI+aarc7nT/9hhrkbWDcx8NMf1l9WPJrtey4pdt8bX4eiaxEuibk4Q8aCLVcERIWLZnf11TQKbka2eevCjBce2Vazay1fPGgXoC6jfpJMi118FpkylXQ0Tk32eUvY5fT479hqVDaFZ7h2wCNI9wM8j9EBFROiiu5BcNGgYVzZmCX2QGVtaA5vw7UhScgtsMe6WnTR/uuoM4iBJ6EawaBfq7+ZPI1UHEUwvghpqHGFZqcPHLX9PNCtNRGz/t3wasxokzw9wXtvL5+aDrCc9fC/XbFFTCPtJh4vQRGQAh+IJdXZhAf0QqAkXkHVEDBD8lNOi7jw+dPJPb/7dip8rFaQZMie3uDIBRrhNq8bjhsu2ibOdriyH7hVnz6Mg11ZLUNATBuLlOgkB16/fDt9YmBPmnpryOLCg+CBku7Z/dT6kTofTEBnHgUYXHDPynJiRnKN8xGsuSz++5r/ztGwyU5bzocvl/dkhiulTnWaFEqxtyLPRReCXtS/tDWWggNBUmamwj0xzJah63XOiVwzbZXvwkrTpjV3waPghN7tcHBhWl4GugrHxNV+XafwwtgMlM1i1gCyhMHHWc2x1UN9NQ=
  distributions: sdist
  skip_cleanup: true
  on:
    repo: KCOM-Enterprise/cfn-square
    branch: master
    python: '3.5'
