sudo: false
language: python
python:
- '3.5'
- '3.6'
before_install:
- git fetch --unshallow
install:
- pip install pip pybuilder coveralls --upgrade
- pyb install_dependencies
script:
- pyb -X run_unit_tests
after_success:
- coveralls --verbose
before_deploy:
- pyb -X package

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "0HWusE4jKLqkLzRwiX2czz8ZyAngIHuF/j9FEj/sy19OT8/Ll3C2KCRLdpVK7fmyOg6fFyvbXtjpEhFsHA2o2UyiCYsit0p7uuZ0k6zSJRdiXOnlEOcDivxSZ8CeI0SK5qhC4hIpYNFjvQxXsr04dsf50RT9wdsCVlB01c8og3gGLeLjkKDdY+1MX8Pfabmap0N5zIS79WB91Zt8tm70kml5eOwk8bsZDzsjzRFFXEHDyIDWnkOOZplIr7CDf+YFFBmrX9yPVFFnT9ZGhUQ++HO8yD7XdTK2nFssHgouZ+FJiBfHKsoFJBwWUszvizjSzK153Mmll8zMXZ1wpuiImKlo1hP7S3ylztEUyLnVe+5YdXd6jbAWfWqQEP3KiL1laZxIAMMObo7F5q8TEHAIuzF1NK5//Q0wUXr2RjNrEVlISnP3l3AISWUj1BMG4DT6tcCEHtHBkyoxHKJMjDr1Q0aRVrYoMf1Wx2NuApA5Edj4Vqitg5wrcR7wfyhb2dWxIKvGMgLFJ0nwVEyy0XRHrvwfAQv5Fioo8qH1McnMudmiH2lTcDz6QodHAZmRzcqhWJ0euJm9NFKFSws+5AU7PY5UlHvK4hxvzE/h7aaYAjPNMG7EuND24VwnAyyICjccP6bbgNzlha8jP2wUNJhzerG58Ic1BxzetEd2uC6oJVU="

  distributions: sdist 
  skip_cleanup: true
  on:
    repo: KCOM-Enterprise/cfn-square
    branch: master
    python: '3.5'
