sudo: false
language: python
python:
- '3.4'
- '3.5'
- '3.6'
before_install:
- git fetch --unshallow
install:
- pip install pip pybuilder coveralls --upgrade
- pyb install_dependencies
script:
- pyb -X run_unit_tests
after_success:
- coveralls --verbose
before_deploy:
- pyb -X package
deploy:
  provider: pypi
  user: steveparker-kcom
  distributions: sdist
  skip_cleanup: true
  on:
    repo: KCOM-Enterprise/cfn-square
    branch: master
    python: '3.5'
  password:
    secure: CD7ZdWHsL42EPsiClV4zU8xFfGHEAYcgcD4dCrXI+d25RuKI2Yr8fMUZNLqPH8kVIjzcRJ2sHve/LQK+imCVSpqc94GkULGMssa/AUbkw1kM7F88YDDBFK2l9ngNlV2RzUoNUOm5Vex5KKgxlbTmd79xcJz7vpUv0705V52lRgcDZsrI7MjMDgs/i2yNaRxsgmKSyMRkMoFCCODfc6386l1zwo3kw1o7oPAlTvYtAIwRd+G20gJw4Qy7yx4tKBGM5VtzrfoS1IWH+hJm179t1ZcOUJkdZ2MLKUPk8gKw4hvAIi4D+/At+IPHPNhBHt++sFyyrTWK2ocoQC8cNOluP52QLfOobn0RO+6rNziCmL59V1o2z0LSsyb2NSf3TzTPmqq1ECc2ckzIDFHyg3DIn5xcEGXQa8KG6jv5OZDmsvn9rJJHhE7LmYc63Nj6/cgdCzOZKIVekFfUqiuJo5KfhDIlivXbdCMnfQGQmW+aLfVIjGA17OiDlJahsOY4JzBZOtuMJHqOw4UldZAfk7WHtMG5chsfObRztJfQxDDvQ0h8j6eJCXzS0skX1cdtx0PI/NBnfLd3jtt886S0wIx6lCvhJuaMX/c2GWXw5DLLEamo/8bLeBICzt7hOCNEfrAC8k/MMuLm0ezaSVE+DKf3R5ey2MFDl09OaUIL3oVNh8w=
