sudo: false
language: python
python:
- '3.5'
- '3.6'
before_install:
- git fetch --unshallow
install:
- pip install pip pybuilder coveralls --upgrade
- pyb install_dependencies
script:
- pyb -X run_unit_tests
after_success:
- coveralls --verbose
before_deploy:
- pyb -X package

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "umDKWX2WmiIyUD4mseJqIEzIQMBBmJiNzT8bzLDEMlbNZcAVHgbdvV+MzRkqERVoQ0L1T2bi1+xA9a+nypOIuXv2ZDRkrOcj/qYF+3hPOw/MVOndlA6gmgoZfxOExj/9M/r5L+HwMRXrdPtnaSoJnQpvut9YPlwE8Zp13vLLgDOl7mgQQ3pf06zlXHto/cr7ccU2Hgs1AnKG+imzHj5vuKW/YValVLAcMJQvLOU0agS6To2a0tdJV1pcmd26q+4MlQ+APXGys1mmyRQRmS3NTkrjzJ9qTzviqH5fAgoKnAGMaMWvj37TEA0DMKuxOb9wvEg5nNSPqV7cHbGEq+InFxYZ4mtjtLYMl+maof105L2upueb0VQyB8qB4A6skC+IyrjIOsIgYj/fF2Fg7mmU02EOUIjX0AoXt/RqACixQBedzi21UHCDfaoMrBArBo+Hpek130kMEGSjVUIqKWYushzaJfR3Q5z4d2uvcbN6tFPMsiRBKFPOrMN8yj7a6qh8EnX0mJ+y2/r5nD2xqL4X3CRgC/Absmek+joX4f5+4nouK5if8Hsnb58sflLFXMXIyDXIWn1IyFgxXVHYHUW7dHJI0phVyTr65T7x+pVjeAX/eN8GKmoiW0sMR0i7XgnioayMxSaQDOcyrUZz1tTOgE0bqE2qMWv3gKpyWfmQdV0="

  distributions: sdist 
  skip_cleanup: true
  on:
    repo: KCOM-Enterprise/cfn-square
    branch: master
    python: '3.5'
