sudo: false
language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- pypy
before_install:
- git fetch --unshallow
install:
- pip install pip pybuilder coveralls --upgrade
- pyb install_dependencies
script:
- pyb -X run_unit_tests
after_success:
- coveralls --verbose
before_deploy:
- pyb -X package
deploy:
  provider: pypi
  user: steveparker-kcom
  password:
    secure: BFrgyyPxaqPQyTqlhW5z93PfZS/xMVbcvTGNCXUOYtUNd38cjh7QM8vI6sWy69bns/miqsrnKVoIfgMYpkTULne1gZkc/4SyewPiEn96e5/jCD+XmFxsyo/R2Hdv4TQF11kntOTVpp9tPHp+dm+OnVF4wAr/3uYgaDDbr5XGApyc6/U5cudfO45n0oOoTqzzhOtXaY4EtoIKiDfEUh+O7hlzIef4DcNByzjNl4I2qix3cIGLfstaasSKirck385VqsJdoCFM9/yXu8YWFdu6/KiqzWITBBqoPJ7A+nNV+RbQYs8fR/NN0sM+vDXONT57nHYO2z9Rcq2nH0+NcX9f3ECn2eG4AYNsOk4cEowtk+cCiPeAqqp6e7WPsM7gFPkhdWPitvQTFssXoIUHkQYUVkwR/2xZGo7u+gTpZeMDAqoBpSgiv8NTo4EBg68+KR2NmvY/OPj9P4+n3aRbHKFPwCMc1/pJ3qIJYZaXgdRp5IaGJzBt84qirB7Bvml+XRxF9YGbkPp1O2ihQ4KaU7B0lVr81PjQ1CnI0p0jFRgO+fi5DrYYzQMtTqSOOlKQmV8IEdegIskg/A/MNyzbhsqRm55ldcQJBqH9oC7vsYIuwl7skVtf1fNm9tjafCSy+q/EFX/h0Si8ou1EXPUOqFWc8Ga7Z8Az//Txo9SQPI2Ydo4=
  distributions: sdist
  skip_cleanup: true
  on:
    repo: Smart421/cfn-square
    branch: master
    python: '3.5'
